library(tidyverse)
wineType <- c( rep("White", times = 346), rep("Red", times = 359))
names(wineType) <- c("Aidani", "Zlahtina", "Assyrtico", "Muscatel", "Zierfandler-Rotgipfler", "Airen", "Albana", "Albanello", "Tempranillo Blanco", "Zibibbo", "Albariño", 
                      "Tamianka", "Roviello", "Zelen", "Yapincak", "Xynisteri", "Xarel-lo", "White Riesling", "White Port", 
                      "White Blend", "Aligoté", "Petit Meslier", "Pinot Gris-Gewürztraminer", "Alsace white blend", "Altesse", "Welschriesling", 
                      "Alvarinho", "Alvarinho-Chardonnay", "Pinot Blanc-Pinot Noir", "Xinisteri", "Pinot Blanc-Viognier", "Trajadura", "Ansonica", "Weissburgunder", "Antão Vaz", 
                      "Apple", "Viura-Verdejo", "Viura-Chardonnay", "Viura", "Arinto",  "Arneis", "Vitovska", 
                      "Vital", "Asprinio", "Malagouzia", "Assyrtiko", "Pinot Blanc-Chardonnay", "Viosinho", "Athiri", "Austrian white blend", 
                      "Auxerrois", "Avesso",  "Azal", "Viognier-Valdiguié", "Viognier-Roussanne", 
                      "Viognier-Marsanne", "Bacchus", "Viognier-Grenache Blanc", "Viognier-Gewürztraminer", 
                      "Viognier-Chardonnay", "Viognier", "Vilana", "Vignoles", "Vidal Blanc", "Vidal", 
                      "Biancale", "Biancolella", "Biancu Gentile", "Bical", "Vespaiolo", "Vernaccia", 
                      "Vermentino", "Verduzzo Friulano", "Verduzzo", "Verdosilla", "Verdil", "Verdicchio", 
                      "Verdelho", "Verdejo-Viura", "Verdejo-Sauvignon Blanc", "Verdejo", "Verdeca", 
                      "Veltliner", "Valvin Muscat", "Ugni Blanc-Colombard", "Ugni Blanc", "Turbiana", 
                      "Tsolikouri", "Trousseau Gris", "Treixadura", "Trebbiano Spoletino",
                      "Trebbiano di Lugana", "Trebbiano", "Traminette", "Traminer", "Torrontés", 
                      "Torontel", "Torbato", "Tokay Pinot Gris", "Tokay", "Tokaji", "Tocai Friulano", 
                      "Tocai", "Timorasso", "Thrapsathiri", "Terrantez", "Tamjanika", "Tămâioasă Românească", 
                      "Blanc du Bois","Symphony", "Bombino Bianco", "Sylvaner", "Sparkling Blend", "Siria", 
                      "Silvaner-Traminer", "Silvaner", "Siegerrebe", "Sideritis", "Bordeaux-style White Blend", 
                      "Bual", "Sherry", "Seyval Blanc", "Sercial", "Zinfandel", "Semillon-Sauvignon Blanc", 
                      "Semillon-Chardonnay", "Sémillon", "Scheurebe", "Savatiano", "Savagnin", "Sauvignonasse", 
                      "Sauvignon-Sémillon", "Sauvignon Musqué", "Sauvignon Gris", "Sauvignon Blanc-Verdejo", 
                      "Sauvignon Blanc-Semillon", "Sauvignon Blanc-Sauvignon Gris", 
                      "Sauvignon Blanc-Chenin Blanc", "Sauvignon Blanc-Chardonnay", "Sauvignon Blanc-Assyrtiko",
                      "Sauvignon Blanc", "Sauvignon", "Sämling", "Sacy", "Ryzlink Rýnský", "Caprettone", 
                      "Roussanne-Marsanne", "Roussanne-Viognier", "Roussanne-Grenache Blanc", "Roussanne", 
                      "Rotgipfler", "Roter Veltliner", "Roter Traminer", "Roscetto", "Carricante", 
                      "Romorantin", "Rolle", "Roditis-Moschofilero", "Roditis", "Robola", "Rkatsiteli", 
                      "Rivaner", "Riesling-Chardonnay", "Riesling", "Catalanesca", "Catarratto", "Cayuga", 
                      "Cerceal", "Cercial",  "Rieslaner", "Ribolla Gialla", "Champagne Blend", 
                      "Rhône-style White Blend", "Chardonel", "Chardonnay", "Chardonnay-Albariño", 
                      "Chardonnay-Pinot Blanc", "Chardonnay-Pinot Gris", "Chardonnay-Riesling", 
                      "Chardonnay-Sauvignon", "Chardonnay-Sauvignon Blanc", "Chardonnay-Semillon", 
                      "Chardonnay-Viognier", "Chardonnay Weissburgunder", "Chasselas", "Chenin Blanc", 
                      "Chenin Blanc-Chardonnay", "Chenin Blanc-Sauvignon Blanc", "Rebula", 
                      "Chenin Blanc-Viognier", "Chinuri", "Rabigato", "Clairette", "Cococciola", 
                      "Coda di Volpe", "Códega do Larinho", "Provence white blend", "Colombard", 
                      "Colombard-Sauvignon Blanc", "Prosecco", "Colombard-Ugni Blanc", "Cortese", 
                      "Prié Blanc", "Premsal", "Dafni", "Posip", "Debit", "Diamond", "Doña Blanca", 
                      "Portuguese White", "Portuguese Sparkling", "Edelzwicker", "Elbling", "Durella", 
                      "Emir", "Erbaluce", "Encruzado", "Plyto", "Falanghina", "Piquepoul Blanc", "Favorita", 
                      "Feteasca", "Feteasca Regala", "Fernão Pires", "Pinot-Chardonnay", "Fiano", 
                      "Folle Blanche", "Franconia", "Fumé Blanc", "Friulano", "Furmint", "Garganega", 
                      "Pinot Gris", "Pinot Grigio-Sauvignon Blanc", "Pinot Grigio", "Pinot Blanc", 
                      "Pinot Bianco", "Garnacha Blanca", "Pinot Auxerrois", "Pignoletto", "Pigato", 
                      "Picpoul", "Picolit", "Picapoll", "Gelber Traminer", "Gelber Muskateller", 
                      "Gewürztraminer",  "Petit Manseng", "Petit Courbu", "Gewürztraminer-Riesling", 
                      "Pecorino", "Glera", "Passerina", "Gouveio", "Godello", "Paralleda", "Pansa Blanca", 
                      "Graevina", "Palomino", "Grauburgunder", "Pallagrello Blanco", "Grechetto", 
                      "Grecanico", "Greco", "Greco Bianco", "Grenache Blanc", "Orangetraube", "Orange Muscat", 
                      "Ondenc", "Nuragus", "Nosiola", "Neuburger", "Nasco", "Nascetta","Narince", "Muskateller", 
                      "Muskat Ottonel", "Muskat", "Muscat of Alexandria", "Muscat d'Alexandrie", "Muscat Canelli", 
                      "Muscat Blanc à Petits Grains", "Muscat Blanc", "Muscat", "Muscadelle", "Muscadel", 
                      "Müller-Thurgau", "Mtsvane", "Moschofilero-Chardonnay", "Moschofilero", "Moscato Giallo", 
                      "Moscato di Noto", "Moscato", "Moscatel de Alejandría", "Moscatel", "Moscadello", "Morio Muskat", 
                      "Grillo", "Gros Manseng", "Morillon", "Gros Plant", "Gros and Petit Manseng", 
                      "Morava", "Hárslevelü", "Grüner Veltliner", "Hondarrabi Zuri", "Insolia", "Inzolia", 
                      "Misket", "Meseguera", "Irsai Oliver", "Merseguera-Sauvignon Blanc", "Jacquère", 
                      "Jampal", "Johannisberg Riesling", "Kangoun", "Kerner", "Kinali Yapincak", "Kisi", 
                      "Melon", "Loin de l'Oeil", "Loureiro", "Loureiro-Arinto", "Mauzac", "Macabeo", 
                      "Macabeo-Chardonnay", "Macabeo-Moscatel", "Maturana", "Madeira Blend", 
                      "Madeleine Angevine", "Marsanne-Viognier", "Marsanne-Roussanne", "Malagousia", 
                      "Malagouzia-Chardonnay", "Marsanne", "Maria Gomes-Bical", "Maria Gomes", "Marawi", 
                      "Manzoni", "Mantonico", "Malvasia-Viura", "Malvasia Istriana", "Malvar", "Malvasia", 
                      "Malvasia Bianca", "Malvasia di Candia", "Abouriou", "Malvasia Nera", "Malvasia Fina", 
                      "Malbec-Tempranillo", "Malbec", "Malbec-Syrah", "Malbec-Tannat", "Malbec-Petit Verdot", 
                      "Mandilaria", "Mansois", "Malbec-Merlot", "Malbec Blend", "Malbec-Cabernet Franc", 
                      "Malbec-Carménère", "Malbec-Cabernet Sauvignon", "Malbec-Cabernet", "Malbec-Bonarda", 
                      "Magliocco", "Kadarka", "Lagrein", "Lemberger", "Listán Negro", "Lambrusco", 
                      "Lambrusco di Sorbara", "Lambrusco Grasparossa", "Lambrusco Salamino", "Karalahna", 
                      "Kekfrankos", "Kuntra", "Kotsifali", "G-S-M", "Kalecik Karasi", "Karasakiz", 
                      "Incrocio Manzoni", "Jacquez", "Durif", "Jaen", "Grenache", "Garnacha-Syrah", 
                      "Grenache Gris", "Grenache-Mourvèdre", "Grenache-Shiraz", "Groppello", "Grignolino", 
                      "Grolleau", "Grenache Blend", "Grenache Noir", "Grenache-Syrah", "Gaglioppo", 
                      "Garnacha", "Gragnano", "Graciano", "Grenache-Carignan", "Garnacha Blend", 
                      "Garnacha-Cariñena", "Gamay Noir", "Garnacha-Tempranillo", "Garnacha-Monastrell", 
                      "Garnacha-Cabernet", "Garnacha Tintorera", "Gamza", "Gamay", "Früburgunder", 
                      "Francisa", "Frappato", "Counoise", "Freisa", "Frankovka", "Forcallà", "Fer Servadou", 
                      "Feteasca Neagra","Agiorgitiko", "Espadeiro", "Dornfelder", "Dolcetto", "Colorino", 
                      "Duras", "Ekigaïna",  "Corvina, Rondinella, Molinara", "Chancellor", "Corvina", 
                      "Charbono", "Chelois", "Ciliegiolo",  "Claret", "Aglianico", "Cinsault", "Zweigelt", 
                      "Cesanese d'Affile", "Centesimino", "Cesanese", "Albarossa", "Aleatico", 
                      "Xinomavro", "Chambourcin", "Alfrocheiro", "Alicante", "Alicante Bouschet", 
                      "Alvarelhão", "Vranec" , "Aragonês", "Aragonez", "Austrian Red Blend", "Babic", 
                      "Babosa Negro", "Baco Noir", "Baga", "Vinhão", "Baga-Touriga Nacional", "Barbera", 
                      "Barbera-Nebbiolo", "Bastardo", "Vidadillo", "Vespolina", "Vermentino Nero", 
                      "Castelão", "Valdiguié", "Uvalino", "Uva di Troia", "Tsapournakos", "Trousseau", 
                      "Trollinger",  "Trincadeira", "Trepat", "Touriga Nacional-Cabernet Sauvignon", 
                      "Touriga Nacional Blend", "Touriga Nacional", "Touriga Franca", "Touriga", 
                      "Tinto Velasco", "Tinto Fino", "Tinto del Pais",  "Tintilia", "Tinta Roriz", 
                      "Tinta Negra Mole", "Tinta Miúda", "Tinta Madeira", "Tinta Francisca", "Tinta Fina", 
                      "Tinta del Toro", "Tinta de Toro", "Tinta Cao",  "Tinta Barroca", "Tinta Amarela", 
                      "Teroldego Rotaliano", "Teroldego", "Teran", "Tempranillo-Tannat", "Tempranillo-Syrah",
                      "Tempranillo-Shiraz", "Tempranillo-Merlot", "Tempranillo-Garnacha", 
                      "Tempranillo-Cabernet Sauvignon", "Tempranillo Blend", "Tempranillo", 
                      "Tannat-Syrah", "Tannat-Merlot", "Tannat-Cabernet Franc", "Tannat-Cabernet", 
                      "Tannat", "Syrah-Viognier", "Syrah-Tempranillo", "Syrah-Petite Sirah", 
                      "Syrah-Petit Verdot", "Syrah-Mourvèdre", "Syrah-Merlot", "Syrah-Malbec", 
                      "Syrah-Grenache-Viognier", "Syrah-Grenache", "Syrah-Carignan", 
                      "Syrah-Cabernet Sauvignon", "Syrah-Cabernet Franc", "Syrah-Cabernet", 
                      "Syrah-Bonarda", "Syrah", "Susumaniello", "Bombino Nero", "St. Vincent", 
                      "St. Laurent", "Spätburgunder", "Souzao", "Sousão",  "Sirica", "Black Monukka", 
                      "Black Muscat","Blatina", "Blauburger", "Blauburgunder", "Blauer Portugieser", 
                      "Blaufränkisch", "Bobal", "Bobal-Cabernet Sauvignon",   "Bogazkere", "Bonarda", 
                      "Bordeaux-style Red Blend", "Shiraz-Viognier", "Shiraz-Tempranillo", 
                      "Shiraz-Roussanne", "Shiraz-Mourvèdre", "Shiraz-Malbec", "Shiraz-Grenache", 
                      "Shiraz-Cabernet Sauvignon", "Shiraz-Cabernet", "Shiraz", "Sciaccerellu", 
                      "Schwartzriesling", "Schiava", "Saperavi-Merlot", "Saperavi", "Bovale", "Brachetto", 
                      "Braucol", "Cabernet", "Cabernet Blend", "Cabernet Franc", 
                      "Cabernet Franc-Cabernet Sauvignon", "Cabernet Franc-Carmenère", 
                      "Cabernet Franc-Lemberge", "Cabernet Franc-Malbec", "Cabernet Franc-Merlot", 
                      "Cabernet-Malbec", "Cabernet Merlot", "Cabernet Moravia", "Cabernet Pfeffer", 
                      "Cabernet Sauvignon", "Cabernet Sauvignon-Barbera", "Cabernet Sauvignon-Cabernet Franc",
                      "Cabernet Sauvignon-Carmenère", "Cabernet Sauvignon Grenache",
                      "Cabernet Sauvignon-Malbec", "Cabernet Sauvignon-Merlot", 
                      "Cabernet Sauvignon-Merlot-Shiraz",  "Cabernet Sauvignon-Sangiovese", 
                      "Cabernet Sauvignon-Shiraz", "Cabernet Sauvignon-Syrah", 
                      "Cabernet Sauvignon-Tempranillo", "Cabernet-Shiraz", "Çalkarasi", "Canaiolo", 
                      "Cannonau", "Sangiovese-Syrah", "Sangiovese-Cabernet Sauvignon", "Sangiovese Grosso", 
                      "Sangiovese Cabernet", "Sangiovese", "Sagrantino", "Rufete", "Ruché", "Carcajolu", 
                      "Carignan", "Carignane",  "Carignan-Grenache", "Rosenmuskateller", "Rosé", 
                      "Carignano", "Carignan-Syrah", "Carineña",  "Cariñena-Garnacha", "Carmenère", 
                      "Carmenère-Cabernet Sauvignon", "Carmenère-Syrah","Rosato", "Rosado", "Casavecchia", 
                      "Rhône-style Red Blend", "Refosco", "Red Blend", "Rebo", "Rara Neagra", "Ramisco", 
                      "Raboso", "Pugnitello", "Prunelard", "Prugnolo Gentile", "Provence red blend", 
                      "Primitivo", "Prieto Picudo", "Poulsard", "Portuguiser", "Portuguese Rosé", 
                      "Portuguese Red", "Port", "Plavac Mali", "Pinotage-Merlot", "Pinotage", 
                      "Pinot Noir-Syrah", "Pinot Noir-Gamay", "Pinot Noir", "Pinot Nero", "Pinot Meunier", 
                      "Pignolo", "Piedirosso", "Petite Verdot", "Petite Sirah", "Petit Verdot", "Perricone", 
                      "Pedro Ximénez", "Parraleta", "Papaskarasi", "Pallagrello Nero", "Pallagrello", "País",
                      "Otskhanuri Sapere", "Other", "Okuzgozu", "Ojaleshi", "Norton", "Nielluciu", 
                      "Nero di Troia", "Nero d'Avola", "Nerello Mascalese", "Nerello Cappuccio", 
                      "Negroamaro", "Negrette", "Nebbiolo", "Muscat Hamburg", "Mourvèdre-Syrah", 
                      "Mourvèdre", "Moscato Rosa", "Moscatel Roxo", "Moscatel Graúdo", "Montepulciano",  
                      "Monica", "Mondeuse", "Monastrell-Syrah", "Monastrell-Petit Verdot", "Monastrell", 
                      "Molinara", "Mission", "Merlot-Tannat", "Merlot-Syrah", "Merlot-Shiraz", 
                      "Merlot-Petite Verdot", "Merlot-Malbec", "Merlot-Cabernet Sauvignon", 
                      "Merlot-Cabernet Franc", "Merlot-Cabernet", "Merlot", "Meritage", "Mencía", 
                      "Melnik", "Mazuelo", "Mavrud", "Mavroudi", "Mavrotragano", "Mavrokalavryta", 
                      "Mavrodaphne", "Mataro", "Marzemino", "Argaman", "Marselan", "Marquette", "Vranac", "Tinta del Pais",
                      "Tempranillo-Malbec", "Muscadine", "Merlot-Grenache", "Merlot-Argaman", "Cabernet-Syrah")
                      

wineType[wine_data$variety]

wine_data$color <- wineType[wine_data$variety]
